name: Playwright Tests
on:
  pull_request:
jobs:
  test_setup:
    name: Test setup
    runs-on: ubuntu-latest
    permissions: read-all
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@main
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 300
  test_e2e:
    needs: test_setup
    name: Playwright tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "pnpm"
      - run: pnpm install
      - run: npx playwright install --with-deps
      - run: npx prisma db push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: pnpm run test:e2e
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PLAYWRIGHT_TEST_BASE_URL: ${{ needs.test_setup.outputs.preview_url }}
          OTP_SECRET: ${{ secrets.OTP_SECRET }}
          OTP_USER: ${{ secrets.OTP_USER }}
          OTP_SERVICE: ${{ secrets.OTP_SERVICE }}
