name: Playwright Tests
on:
  pull_request:
jobs:
  test_e2e:
    name: Playwright tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "pnpm"
      - uses: actions/cache@v2
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: pnpm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - run: npx playwright install-deps
        if: steps.playwright-cache.outputs.cache-hit == 'true'
      - name: Wait for Cloudflare Pages preview deployment to be ready
        uses: WalshyDev/cf-pages-await@v1
        id: waitForCfPagesPreviewDeployment
        with:
          apiToken: ${{ secrets.cloudflare_wait_for_deploy_api_token  }}
          accountId: ${{ secrets.cloudflare_account_id }}
          project: ${{ secrets.cloudflare_project_name }}
      - run: pnpm run test:e2e
        env:
          DATABASE_URL: ${{ secrets.database_url }}
          DATABASE_HOST: ${{ secrets.database_host }}
          DATABASE_USERNAME: ${{ secrets.database_username }}
          DATABASE_PASSWORD: ${{ secrets.database_password }}
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitForCfPagesPreviewDeployment.outputs.url }}
          OTP_SECRET: ${{ secrets.OTP_SECRET }}
          OTP_USER: ${{ secrets.OTP_USER }}
          OTP_SERVICE: ${{ secrets.OTP_SERVICE }}
