name: Playwright Tests
on:
  pull_request:
jobs:
  test_e2e:
    name: Playwright tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "pnpm"
      - run: pnpm install
      - run: npx playwright install --with-deps
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@main
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 300
      - run: pnpm run test:e2e
        env:
          DATABASE_URL: ${{ secrets.database_url }}
          DATABASE_HOST: ${{ secrets.database_host }}
          DATABASE_USERNAME: ${{ secrets.database_username }}
          DATABASE_PASSWORD: ${{ secrets.database_password }}
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
          OTP_SECRET: ${{ secrets.OTP_SECRET }}
          OTP_USER: ${{ secrets.OTP_USER }}
          OTP_SERVICE: ${{ secrets.OTP_SERVICE }}
