name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_e2e:
    services:
      database:
        image: mjmammoth/libsql-server
        ports:
          - 5001:5001
          - 8080:8080
    name: Playwright tests
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy
    env:
      PLAYWRIGHT_TEST_BASE_URL: "http://localhost:3000"
      TURSO_CONNECTION_URL: "libsql://localhost:5001"
      NXCACHE_AWS_ACCESS_KEY_ID: ${{secrets.nxcache_aws_access_key_id}}
      NXCACHE_AWS_SECRET_ACCESS_KEY: ${{secrets.nxcache_aws_secret_access_key}}
      NXCACHE_AWS_ENDPOINT: ${{secrets.nxcache_aws_endpoint}}
      NXCACHE_AWS_REGION: ${{secrets.nxcache_aws_region}}
      NXCACHE_AWS_BUCKET: ${{secrets.nxcache_aws_bucket}}
      NXCACHE_AWS_FORCE_PATH_STYLE: ${{secrets.nxcache_aws_force_path_style}}
      OTP_SECRET: ${{ secrets.OTP_SECRET }}
      OTP_USER: ${{ secrets.OTP_USER }}
      OTP_SERVICE: ${{ secrets.OTP_SERVICE }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 7
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm drizzle-kit push:sqlite
      - run: HOME=/root pnpm run test:e2e --skipInstall
